# Generated by Django 5.0.3 on 2024-03-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="workoutexercise",
            unique_together={("exercise", "workout")},
        ),
    ]
