# Generated by Django 5.0.3 on 2024-03-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0002_alter_workoutexercise_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
