# Generated by Django 5.0.3 on 2024-04-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workout", "0004_workout_session"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workout",
            name="user",
        ),
    ]
